# 🧠 Day 04 – NumPy Basics for AI Math

In [2]:
import numpy as np
np.__version__
print('✅ NumPy imported successfully')

✅ NumPy imported successfully


## 🔢 Arrays vs Lists

In [3]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print('Python List:', lst)
print('NumPy Array:', arr)
print('Type:', type(arr))

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


## 🧮 Element-wise Math

In [4]:
print('List * 2 (repeats list):', lst * 2)
print('Array * 2 (multiplies):', arr * 2)
print('Array + 10:', arr + 10)
print('Array ** 2:', arr ** 2)

List * 2 (repeats list): [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array * 2 (multiplies): [ 2  4  6  8 10]
Array + 10: [11 12 13 14 15]
Array ** 2: [ 1  4  9 16 25]


## 🔁 Slicing & Indexing

In [5]:
print('First element:', arr[0])
print('Slice [1:4]:', arr[1:4])
print('Every other:', arr[::2])

First element: 1
Slice [1:4]: [2 3 4]
Every other: [1 3 5]


## 🔲 Matrix Operations (2D Arrays)

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)
print('Shape:', matrix.shape)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [7]:
print('Element-wise square:\n', matrix ** 2)
print('Transpose:\n', matrix.T)

Element-wise square:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
# Dot product (matrix multiplication)
print('Dot with itself:\n', matrix @ matrix)

Dot with itself:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## 🏎️ Bonus: Speed test (vectorization wins)

In [9]:
%%timeit
x = np.arange(1_000_000)
y = x * 2

1.03 ms ± 25.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
%%timeit
lst = list(range(1_000_000))
out = [v * 2 for v in lst]

25 ms ± 435 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
